# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: entreheart
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: tenanttext
service: hello-world-python

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "*"

layers:
  dependencies:
    path: layers/python
    description: Python dependencies for Lambda function
    compatibleRuntimes:
      - python3.11

functions:
  hello:
    handler: handler.hello
    layers:
      - !Ref DependenciesLambdaLayer
    events:
      - httpApi:
          path: /hello
          method: get 